// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package bot

import (
	"keyboard-api-go/api/bot"
)

type ControllerV1 struct{}

func NewV1() bot.IBotV1 {
	return &ControllerV1{}
}
