// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package secure

import (
	"keyboard-api-go/api/secure"
)

type ControllerV1 struct{}

func NewV1() secure.ISecureV1 {
	return &ControllerV1{}
}
