// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package system

import (
	"keyboard-api-go/api/system"
)

type ControllerV1 struct{}

func NewV1() system.ISystemV1 {
	return &ControllerV1{}
}
