// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chain

import (
	"keyboard-api-go/api/chain"
)

type ControllerV1 struct{}

func NewV1() chain.IChainV1 {
	return &ControllerV1{}
}
