// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"keyboard-api-go/internal/dao/internal"
)

// internalEarningDao is internal type for wrapping internal DAO implements.
type internalEarningDao = *internal.EarningDao

// earningDao is the data access object for table earning.
// You can define custom methods on it to extend its functionality as you wish.
type earningDao struct {
	internalEarningDao
}

var (
	// Earning is globally public accessible object for table earning operations.
	Earning = earningDao{
		internal.NewEarningDao(),
	}
)

// Fill with you ideas below.
