// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"keyboard-api-go/internal/dao/internal"
)

// internalFriendMsgDao is internal type for wrapping internal DAO implements.
type internalFriendMsgDao = *internal.FriendMsgDao

// friendMsgDao is the data access object for table friend_msg.
// You can define custom methods on it to extend its functionality as you wish.
type friendMsgDao struct {
	internalFriendMsgDao
}

var (
	// FriendMsg is globally public accessible object for table friend_msg operations.
	FriendMsg = friendMsgDao{
		internal.NewFriendMsgDao(),
	}
)

// Fill with you ideas below.
