// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"keyboard-api-go/internal/dao/internal"
)

// internalHoldDao is internal type for wrapping internal DAO implements.
type internalHoldDao = *internal.HoldDao

// holdDao is the data access object for table hold.
// You can define custom methods on it to extend its functionality as you wish.
type holdDao struct {
	internalHoldDao
}

var (
	// Hold is globally public accessible object for table hold operations.
	Hold = holdDao{
		internal.NewHoldDao(),
	}
)

// Fill with you ideas below.
