// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"keyboard-api-go/internal/dao/internal"
)

// internalSystemSettingDao is internal type for wrapping internal DAO implements.
type internalSystemSettingDao = *internal.SystemSettingDao

// systemSettingDao is the data access object for table system_setting.
// You can define custom methods on it to extend its functionality as you wish.
type systemSettingDao struct {
	internalSystemSettingDao
}

var (
	// SystemSetting is globally public accessible object for table system_setting operations.
	SystemSetting = systemSettingDao{
		internal.NewSystemSettingDao(),
	}
)

// Fill with you ideas below.
