// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"keyboard-api-go/internal/dao/internal"
)

// internalWorkRecordDao is internal type for wrapping internal DAO implements.
type internalWorkRecordDao = *internal.WorkRecordDao

// workRecordDao is the data access object for table work_record.
// You can define custom methods on it to extend its functionality as you wish.
type workRecordDao struct {
	internalWorkRecordDao
}

var (
	// WorkRecord is globally public accessible object for table work_record operations.
	WorkRecord = workRecordDao{
		internal.NewWorkRecordDao(),
	}
)

// Fill with you ideas below.
